=== johanjordaan/rembrandt/schemas/colourSchemeSchema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type":"object",
  "additionalProperties": false,
  "properties":{
    "images": {
      "type":"array",
      "items":{
        "type":"object",
        "additionalProperties": false,
        "properties":{
          "ref":{"type":"string"},
          "url":{
            "type":"string",
            "format":"uri-reference"
          }
        }
      }
    },
    "recipes": {
      "type":"array",
      "items":{
        "type":"object",
        "additionalProperties": false,
        "properties":{
          "ref":{
            "type":"string"
          },
          "recipeItems":{
            "type":"array",
            "items":{
              "type":"object",
              "additionalProperties": false,
              "properties":{
                "colour":{"type":"string"},
                "technique":{"type":"string"},
                "notes":{"type":"string"}
              }
            }
          }
        }
      }
    },
    "links": {
      "type":"array",
      "items":{
        "type":"object",
        "additionalProperties": false,
        "properties":{
          "ref":{
            "type":"string"
          },
          "imageRef":{
            "type":"string"
          },
          "recipeRef":{
            "type":"string"
          }
        }
      }
    },
    "layouts":{
      "type":"array",
      "items":{
        "type":"object",
        "additionalProperties": false,
        "properties":{
          "ref":{"type":"string"},
          "images":{
            "type":"array",
            "items":{
              "type":"object",
              "additionalProperties": false,
              "properties":{
                "imageRef":{"type":"string"},
                "position":{
                  "type":"object",
                  "properties":{
                    "x":{"type":"number"},
                    "y":{"type":"number"}
                  }
                }
              }
            }
          },
          "recipes":{
            "type":"array",
            "items":{
              "type":"object",
              "additionalProperties": false,
              "properties":{
                "recipeRef":{"type":"string"},
                "position":{
                  "type":"object",
                  "properties":{
                    "x":{"type":"number"},
                    "y":{"type":"number"}
                  }
                }
              }
            }
          },
          "links":{
            "type":"array",
            "items":{
              "type":"object",  
              "additionalProperties": false,
              "properties":{
                "linkRef":{"type":"string"},
                "position":{
                  "type":"object",
                  "additionalProperties": false,
                  "properties":{
                    "x":{"type":"number"},
                    "y":{"type":"number"}
                  }
                }
              }
            }
          }
        }
      }
    }
  }    
}

=== johanjordaan/rembrandt/data/skeleton.json
{
  "images": [
    {
      "ref":"main",
      "url": "/data/images/main.jpg"
    },
    {
      "ref":"bone_closeup",
      "url": "/data/images/x.jpg"
    }
  ],
  "recipes":[
    {
      "ref":"bone",
      "recipeItems":[
        {
          "colour":"Wraith Bone",
          "technique":"Base",
          "notes":"Spray can"
        },
        {
          "colour":"Seraphim Sepia",
          "technique":"Shade",
          "notes":""
        },
        {
          "colour":"Zandri Dust",
          "technique":"DryBrush",
          "notes":"Heavy"
        },
        {
          "colour":"Palid Wytch Flesh",
          "technique":"DryBrush",
          "notes":"Light, Down Strokes"
        }
      ]
    }
  ],
  "links":[
    {
      "ref":"main_bone",
      "imageRef":"main",
      "recipeRef":"bone"
    },
    {
      "ref":"bone_closeup_bone",
      "imageRef":"bone_closeup",
      "recipeRef":"bone"
    }
  ],
  "layouts":[
    {
      "ref":"layout1",
      "images":[{
        "imageRef":"main",
        "position":{
          "x":100,
          "y":40
        }
      },
      {
        "imageRef":"bone_closeup",
        "position":{
          "x":100,
          "y":10
        }
      }],
      "recipes":[{
        "recipeRef":"bone",
        "position":{
          "x":160,
          "y":10
        }
      }],
      "links":[{
        "linkRef":"main_bone",
        "position":{
          "x":20,
          "y":40
        }
      },
      {
        "linkRef":"bone_closeup_bone",
        "position":{
          "x":10,
          "y":100
        }
      }]
    }  
  ]
}
